### ISSUE TITLE
Format images (stories & homepage)

### ISSUE THREAD

**Issue by Nikomus** [neontribe/ca-hospice-hope#1]
Resize and compress story images.

Plan
- [ ] Choose dimensions and format, from existing images
- [ ] Resize and compress, testing for visual quality
- [ ] Include the images in brand repo

**Comment by rosejbon** [comment]
@Nikomus would it be possible to combine this picture: https://drive.google.com/file/d/1iipPwx37NvJZqBq5MyBQVH-4LJMPQSkg/view?usp=sharing and this picture: https://drive.google.com/file/d/1zs_jke-KpkyHmPVcgGxQg8YeFyaN7NRJ/view?usp=sharing for the front picture on the homepage?

**Comment by Hoolean** [comment]
All images are comfortably visible with no obvious visual artifacts.

On the office Wi-Fi, personally lacking ethernet, I've had a solid opportunity to see how smoothly images do or don't load on a troubled network connection. Most images are smaller than 200kB, although a few still stood out in particular:

* [ ] Homepage banner (1.03MB PNG)
* [ ] **The Haven** logo (351.86kB SVG)
* [ ] **Comic Relief** logo (277.46kB SVG)
* [ ] Story thumbnails have a fairly high resolution, although perhaps this is appropriate given the popularity of high-DPI displays

Does this all look okay?
