### ISSUE TITLE
Get in contact page

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#10]
## Description

During our research we agreed that we want a form online so people can easily refer or ask questions

**Preview of Typeform form:** https://hospicehope.typeform.com/to/rGEewl

## Plan

- [ ] Embed form into its own page
- [ ] Add copy for page: 
>If you'd like us to get in touch with you about Hope House or the Support Cafe, please give us a few details.
- [ ] Check accessibility of form

## Acceptance Criteria

- [x] Form submissions are received correctly
- [x] The form can be filled out

**Comment by katjam** [comment]
@roseb04 do you have an embed code for that form?

**Comment by rosejbon** [comment]
Is this the code you are looking for:

`<div class="typeform-widget" data-url="https://hospicehope.typeform.com/to/rGEewl" style="width: 100%; height: 500px;"></div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script> <div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;"> powered by <a href="https://admin.typeform.com/signup?utm_campaign=rGEewl&utm_source=typeform.com-14340684-Basic&utm_medium=typeform&utm_content=typeform-embedded-poweredbytypeform&utm_term=EN" style="color: #999" target="_blank">Typeform</a> </div>`

**Comment by rosejbon** [comment]
Let me know if that doesn't work, but cross fingers it does :)

**Comment by rosejbon** [comment]
We are not going to embed the form as an iframe because of accessibility. We will keep it as redirecting to the typeform for now and discuss with Liz when she gets back.

**Comment by rosejbon** [comment]
Closing because of above comment
