### ISSUE TITLE
Phone number needs space after call us

### ISSUE THREAD

**Issue by katjam** [neontribe/ca-hospice-hope#100]
## Description
View the home page or call to action at bottom of a story

## Steps to reproduce
1. On a wide viewport (intended for non-phone devices), view that phone number in homepage info section, or at the bottom of a story

![Screenshot_20191002_170345](https://user-images.githubusercontent.com/861172/66060854-429b9d00-e536-11e9-8f08-71a5b901ead2.png)

![Screenshot_20191002_170323](https://user-images.githubusercontent.com/861172/66060859-44fdf700-e536-11e9-8dd5-b0432ba228f8.png)

**Comment by Nikomus** [comment]
@katjam This one could be fixed by changing the copy so that there's a space within the string  "Call us ". If we wanted to force there to always be a space between the prompt and the destination we'd have to fix this over in https://github.com/neontribe/contemplating-action in `CallToAction.elm`.

**Comment by katjam** [comment]
I think in the core repo better.

**Comment by Nikomus** [comment]
I think so to. I'll move it there.
