### ISSUE TITLE
Add Tina's story

### ISSUE THREAD

**Issue by Nikomus** [neontribe/ca-hospice-hope#104]
## User Story
As a user I want to be able to view the new story and content!

Copy:
https://docs.google.com/document/d/1hrzjOKj5lzcSoXU91_fdXFDCTep1g4ML00OjoUh-0Pw/edit

Images:
https://drive.google.com/drive/folders/1mNfSEBVCvRZsl_bORq1nltoCuNf1pyna

## Acceptance
- [x] Tina's story is in the list of stories, and appears first
- [x] Tina's story has four images and copy matching the copy doc
- [x] The related info is as per the copy doc
- [x] The related info links for all stories is as per the copy doc
- [x] The other stories are unchanged

**Comment by j-gynn** [comment]
All AC pass with flying colours! Nice :)
