### ISSUE TITLE
Supporters Page

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#11]
## Description

Copy for supporters page: https://docs.google.com/document/d/1kgRBg7OZijz9y_v66kQWWISvN2Fmn9CK6pmyYMvp6y8/edit?usp=sharing

## Plan

- [ ] Add copy from Google Doc

## Acceptance Criteria

- [x] Copy matches Google Doc
- [x] Comic Relief, Big Lottery Fund and HM Government logos displayed with equal prominence
- [x] CAST's logo is prominent on the page
- [x] Neontribe's logo is visible

**Comment by Hoolean** [comment]
The Hospice Hope logo isn't present but it also isn't in the copy; is this still part of the Acceptance Criteria?

**Comment by rosejbon** [comment]
Probably not anymore, I shall remove it from the AC

**Comment by Hoolean** [comment]
All good then :+1:

I'll mark the issue as tested and ready.

**Comment by rosejbon** [comment]
Thanks @Hoolean :D
