### ISSUE TITLE
Cookie Banner

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#13]
## Description

We need to give people the option to opt into having Google Analytics track them on the site

## Plan

- [ ] Think about how we do this
- [ ] What copy are we using?
- [ ]  Accessibility thought!

##  Acceptance Criteria

- [x] People opt-in not opt-out of cookies
- [x] The cookie notice is clear and easy to find
- [x] Opt in and opt out are given equal weight
- [ ] People can change their minds

**Comment by rosejbon** [comment]
Closing because have put issue in CA repo

**Comment by Hoolean** [comment]
Having attempted to watch user sessions live in Google Analytics and observed cookie usage when navigating around the site, the cookie dialog is good and functional. There are, however, a few issues with our use of Google Analytics:
* [ ] The user must be able to opt-out of cookie usage mid-session.
* [ ] Google Analytics should recognise the user immediately after they press accept. Currently, the user is only recognised after they navigate to another page. Reproducing:
  1. Observe Google Analytics' live data
  2. Press accept -> nothing is logged
  3. Navigate further -> this is logged

A more open question: as we prompt with the cookie banner every session, should pressing `Decline` erase cookies from previous sessions?
