### ISSUE TITLE
Update brand keys & brand style imports

### ISSUE THREAD

**Issue by katjam** [neontribe/ca-hospice-hope#23]
## Description
Sync the `BrandKey.elm` up with the Keys in core code - following the CA updates.

## Plan
- [ ] Make sure the `Keys.elm` and `BrandKeys.elm` have same values
- [ ] Make sure the files we need to override are being included here

**Comment by Hoolean** [comment]
This appears to be a change under-the-hood to keep us up-to-date with `contemplating-action`. As I have not encountered any fatal issues, I'll mark this as tested and correct.
