### ISSUE TITLE
Add related info to all 3 stories

### ISSUE THREAD

**Issue by katjam** [neontribe/ca-hospice-hope#32]
## Description
Refactor story deck in contemplating action to allow related info to be added by brands

**Comment by katjam** [comment]
This is the quickest way I can think of.

In BrandCopy add a function relatedInfo that takes a story id and retuns a list of ints

In StoryDeck replace the hardcoded lists with `relatedInfo 1`

Export `relatedInfo` from BrandCopy and import it into StoryDeck

Hard code the values into BrandCopy.

**Comment by katjam** [comment]
![Screenshot_20190815_142659](https://user-images.githubusercontent.com/861172/63097466-685dea00-bf68-11e9-9c5c-6ad84494a7f7.png)

![Screenshot_20190815_142741](https://user-images.githubusercontent.com/861172/63097506-81ff3180-bf68-11e9-9264-71a5ba3a120a.png)

**Comment by Hoolean** [comment]
The related info was placed correctly when I was testing each story issue (#3, #4 & #5).
