### ISSUE TITLE
Homepage image

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#33]
## Description
We need a front page image that reflects stories. Could we combine this picture https://drive.google.com/file/d/1iipPwx37NvJZqBq5MyBQVH-4LJMPQSkg/view?usp=sharing and this picture: https://drive.google.com/file/d/1zs_jke-KpkyHmPVcgGxQg8YeFyaN7NRJ/view?usp=sharing for the front picture on the homepage?

**Comment by Hoolean** [comment]
Image clear and visible :+1:
