### ISSUE TITLE
Add/remove quotes for Shane and Gary's Stories & make possible for every card to have a message or not

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#34]
## Description
Need to add the messages that accompany Shane and Gary's stories.

The copy for Shane's story is here (missing quote 1 and 3): https://docs.google.com/document/d/1JiyPgfWbhjJCFnEyrXTEdd1CXZ_vz3dj37FHbZCPWz4/edit?usp=sharing

The copy for Gary's story is here (missing quote 1 and 3):
https://docs.google.com/document/d/1Bxti8B3casqFMXRlsFcIewaFkqU2hVVnjG_ZXZyC7S4/edit

## Plan
- [x] Update keys in CA repo
- [ ] Then add copy

**Comment by katjam** [comment]
@HedgehogHolly @roseb04  I've put a PR up in the contemplating action repo which will allow you to do this. You'll have to add the new keys to brand copy and also put in the missing text.

**Comment by Hoolean** [comment]
Copy visible and correct aside from the issue raised in #5. I will wait until it is fixed there before I mark this as tested and ready.
