### ISSUE TITLE
Bugs from Testing

### ISSUE THREAD

**Issue by Nikomus** [neontribe/ca-hospice-hope#44]
## Description
Fix the bugs!

## Bugs
- [x] The keys for the story teaser links are doubled up.
![image](https://user-images.githubusercontent.com/32434620/63095693-c50ad600-bf63-11e9-976e-ffe643ce4a93.png)

- [x] The copyright URL looks like Hospice Hope, but doesn't go to the right destination
- [x] Better markup/ styles for phone cta (raise issue in contemplating action core) - not here
![Screenshot_20190815_141117](https://user-images.githubusercontent.com/861172/63096668-65fa9080-bf66-11e9-9db7-bd81a908ac56.png)
![Screenshot_20190815_141136](https://user-images.githubusercontent.com/861172/63096670-685cea80-bf66-11e9-8732-ecefc1ecf1fc.png)

**Comment by rosejbon** [comment]
Covered by this card: https://github.com/neontribe/contemplating-action/issues/219

**Comment by rosejbon** [comment]
Covered by: https://github.com/neontribe/contemplating-action/issues/218

**Comment by rosejbon** [comment]
Closing because done and covered in other issues

**Comment by Hoolean** [comment]
* The keys for the story teaser links are no longer doubled up.
* The copyright URL is correct.

I will wait for the upstream phone CTA improvement to be implemented and live before I mark this as tested and ready.
