### ISSUE TITLE
Add Shane's Story

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#5]
## Description
Add Shane's Story to the app.

The copy for the story is here: https://docs.google.com/document/d/1JiyPgfWbhjJCFnEyrXTEdd1CXZ_vz3dj37FHbZCPWz4/edit?usp=sharing

Folder for illustrations: https://drive.google.com/drive/folders/1RuLvsbAliXFMyY0pvATFC8lsIl4Ht1Da?usp=sharing

## Plan
- [x] Add copy 
- [x] Add alt text

## Acceptance Criteria 
- [x] Shane's story is listed on the stories
- [x] The copy matches the copy in the Google Doc - https://docs.google.com/document/d/1JiyPgfWbhjJCFnEyrXTEdd1CXZ_vz3dj37FHbZCPWz4/edit?usp=sharing
- [x] Illustrations match the ones in this folder: https://drive.google.com/drive/folders/1RuLvsbAliXFMyY0pvATFC8lsIl4Ht1Da?usp=sharing
- [x] At the end of the story the bite size info shown is 2 and 1
- [x] Will be the first story listed

**Comment by rosejbon** [comment]
Closing because done

**Comment by Hoolean** [comment]
All copy matches aside from:

* [ ]  The second quote, which is an accidental duplication of the first.
Expected: *I love most of the talks that they do and the activities they run, the food.*
Actual: 
![screenshot](https://user-images.githubusercontent.com/2150762/63424327-17d20b00-c406-11e9-8696-5928765edfbd.png)
