### ISSUE TITLE
Liz bugs and copy changes

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#50]
## Description
Liz has emailed over a couple of bugs and copy changes

## Copy changes
1. The “worried it’s not for me” page – the first sentence reads: "Lots of people tell us they’re worried that everyone here will be older than me." It should read “them” instead of “me”
2. The the “Who comes to us” page states conditions such as 'Parkinson's, chronic fatigue or cancer', should be 'Parkinson's, heart failure or cancer'
3. Any mention of 'day therapy' needs to be placed with 'day respite'
4. Hazel and Colin’s story is missing a capital S where other stories have one

## Bug fixes
1. Odd space on the menu bar on mobile
![image](https://user-images.githubusercontent.com/44296500/63180342-fcea4a00-c045-11e9-9e73-f4fa0423b7a2.png)

## Plan

- [x] Update copy in code and master docs
- [x] Discuss menu bar

**Comment by rosejbon** [comment]
Closing because @Nikomus is sorting out the reported bug

**Comment by Hoolean** [comment]
# Testing

## Copy changes
1. [x] The “worried it’s not for me” page – the first sentence reads: "Lots of people tell us they’re worried that everyone here will be older than me." It should read “them” instead of “me”
2. [x] The the “Who comes to us” page states conditions such as 'Parkinson's, chronic fatigue or cancer', should be 'Parkinson's, heart failure or cancer'
3. [x] Any mention of 'day therapy' needs to be placed with 'day respite'
4. [x] Hazel and Colin’s story is missing a capital S where other stories have one


## Bug fixes
1. [x] Odd space on the menu bar on mobile

**Comment by Hoolean** [comment]
We are waiting on a few small changes before everything can be ticked off.

## "Therapy"

Two mentions of "therapy" survived:

* [x] In Gary's second picture
![image](https://user-images.githubusercontent.com/2150762/63425033-924f5a80-c407-11e9-8c59-22538f5b7dc1.png)
* [x] In the alt text of Gary's third picture
*Illustration of a confused man surrounded by thought bubbles. The bubbles contain Gary’s ideas of what Hope House was; there is a drawing of a therapy couch, two older people, a house and question marks.*
## Menu Bar Spacing

* [x] The spacing is still a little strange on the small-viewport menu bar, so I haven't marked this as done yet.
![image](https://user-images.githubusercontent.com/2150762/63425340-3802c980-c408-11e9-8f1b-4dcc7b0646a2.png)

**Comment by rosejbon** [comment]
Good spots @Hoolean!

**Comment by Nikomus** [comment]
@Hoolean I'm fixing the mobile nav spacing (and other call to action styling) over here:
https://github.com/neontribe/contemplating-action/issues/218

I'll let you know when it's merged in 🙂

**Comment by Nikomus** [comment]
@roseb04 when the nav is in mobile mode as in the screenshot above. should the text that says "call us" be a button link than can be clicked to call?

**Comment by rosejbon** [comment]
@Nikomus I think call us makes more sense, I agree

**Comment by Hoolean** [comment]
Changes tested & present as of `v0.0.0-build8`.
