### ISSUE TITLE
Update info sections

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#51]
## Description
Info connected to each story should be as follow

- Shane: "2. What is Hope House?" and "1. Who comes to our sessions"
- Hazel and Collin: "3. What are the support cafes?" and "4. worried it is not for you?"
- Gary: "5. Cost and other practicalities?" and "6. When do sessions take place?"

## Plan
- [ ] Update associated info

**Comment by Hoolean** [comment]
Info connected to each story is linked as described above.
