### ISSUE TITLE
Staging site to be ignored on Google

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#52]
## Description
We need to tell the robots to ignore the staging site

## Plan
- [ ] Step one to achieve this.
- [ ] Step two to achieve this.

**Comment by katjam** [comment]
See also https://github.com/neontribe/contemplating-action/issues/181 I think we plan to do this from core.

**Comment by rosejbon** [comment]
Closing because in core

**Comment by Hoolean** [comment]
Will wait for upstream to test.
