### ISSUE TITLE
Add copy to 'Information to help you'

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#6]
##  Description

We need to add the bite size information we have written based on the user research we have done to the site. 

Link to the copy: https://docs.google.com/document/d/1bPgtH9X-Lq07RnLr_rbLjMMNd0DiSoXAEXWZKMcoMcY/edit?usp=sharing

## Plan

- [x] Add copy 

## Acceptance Criteria

- [x] Copy matched the copy in the Google doc
- [x] All information is selectable from the 'Information to help you' page
- [x] The order of the information is the same as in the Google Doc

**Comment by katjam** [comment]
@Nikomus Need some styling love on the info cards since the hh ones contain lists sometimes. Work in this branch: 0.0/6-info-copy

![image](https://user-images.githubusercontent.com/861172/62834239-523aeb80-bc41-11e9-84ab-67655fd937a3.png)

**Comment by Nikomus** [comment]
@katjam I think the best place for this might be in layout.scss in ca-core so it can be used by other instances.

**Comment by katjam** [comment]
@Nikomus Makes sense. I'll open an issue over there and leave this as it is.
