### ISSUE TITLE
Small Issues

### ISSUE THREAD

**Issue by Hoolean** [neontribe/ca-hospice-hope#62]
These are some small-fry issues I noticed when testing other issues.

* [x] There is an unnecessary space after Part 1 of 4 of Hazel's story.
![image](https://user-images.githubusercontent.com/2150762/63446779-ba07e800-c432-11e9-84a2-3bf602866be1.png)
* [x] Bite-size information is center-aligned, which can make it hard to read.
![image](https://user-images.githubusercontent.com/2150762/63448638-3ea83580-c436-11e9-9c65-5f76b18ed925.png)
* [x] The mobile link in the small-viewport navbar has a doubled `tel:` prefix (`tel:tel:01530222079`), making it unusable on desktop and having it yield an incorrect number on mobile.
![image](https://user-images.githubusercontent.com/2150762/63448699-639ca880-c436-11e9-9e4a-610e32c49379.png)
* [ ] The header stops being a link to the homepage on the homepage itself. This goes against the grain, as most websites preserve the link to provide a consistent "go to home" button and to allow for the homepage URL to be copied easily. (won't fix - but @Nikomus @roseb04 we should check if this is normal/ expected)
![image](https://user-images.githubusercontent.com/2150762/63448763-8b8c0c00-c436-11e9-8a8b-1d59cd93da5b.png)
* [ ] The copyright URL ends up on its own line, in whatever size viewport.
![image](https://user-images.githubusercontent.com/2150762/63449142-621fb000-c437-11e9-9e77-2a444883dc6c.png)
* [x] The website title is briefly "Hospice Hope" instead of "Hospice Hope Stories" before the page finishes loading.
* [ ] In small viewports, with the navbar at the bottom, there is empty space to scroll to even when the page is not sufficiently large.
![image](https://user-images.githubusercontent.com/2150762/63449294-bdea3900-c437-11e9-987c-b599d9647140.png)
* [ ] Our "Call" link for mobile devices is also shown on desktop when the viewport is small enough. On my work laptop (Firefox 68.0.2, Ubuntu 19.04) this link does not go anywhere, as no applications are installed that support the protocol implied by `tel:`. We should probably look into general desktop support for this prefix.
![image](https://user-images.githubusercontent.com/2150762/63617933-aef3ba00-c5e2-11e9-81f2-461d23be4433.png)
* [x] One of the favicon `<link>` elements has a typo'd `rel` attribute.
  `<link rel="favicon" type="image/ico" href="favicon.ico">`
    should be
  `<link rel="icon" type="image/ico" href="favicon.ico">`

## Platform

Firefox 68.0.2, Ubuntu 19.04

**Comment by HedgehogHolly** [comment]
I've sorted the bitesized information text alignment, Rose and I thought the same thing that it would be better for the text to be left aligned. I've kept the title as centered though. 

https://github.com/neontribe/contemplating-action/pull/227

**Comment by HedgehogHolly** [comment]
All problems that haven't been fixed have been carded in separate issues
