### ISSUE TITLE
Call to actions

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#7]
## Description

Call to actions are as follows:

- Phone number - 01530 222079
- 'Get in contact' button which leads to the form

## Plan

- [x] Source icons for call to actions
- [x] call to actions
- [ ] link 'get in contact' to page with embedded typeform

## Acceptance Criteria

- [x] The telephone call to action is 01530 222079
- [x] The 'get in contact' call to action links to a page with an embedded form in it

**Comment by katjam** [comment]
Am working on https://github.com/neontribe/contemplating-action/issues/172 first because that makes sense.

**Comment by katjam** [comment]
@roseb04 for now I have linked out to the form. There is an issue #10 to make the page another time.
