### ISSUE TITLE
Scrollbar on small viewports

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/ca-hospice-hope#75]
## Description
* [ ] In small viewports, with the navbar at the bottom, there is empty space to scroll to even when the page is not sufficiently large.

![image](https://user-images.githubusercontent.com/2150762/63449294-bdea3900-c437-11e9-987c-b599d9647140.png)

**Comment by rosejbon** [comment]
Put in ca backlog

**Comment by rosejbon** [comment]
Closing as added to the backlog of the main CA repo
