### ISSUE TITLE
Publicity for GP surgeries 

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#87]
## Description
Liz will be publicising the site via gp waiting room tv and we have changed the domain name to hopestories.org.uk, so the short videos @HedgehogHolly created will need updating

## Plan
- [x] See if they can be made into mp4 files
- [x] Update link to hopestories.org.uk

**Comment by HedgehogHolly** [comment]
https://trello-attachments.s3.amazonaws.com/5cd2ee3481ed56523d7a2bb9/5cd2f102834acd4cacb5358d/ee74beaa6fbc17cebd74f0d5626ab11a/Shane_sStory.mp4

https://trello-attachments.s3.amazonaws.com/5cd2ee3481ed56523d7a2bb9/5cd2f102834acd4cacb5358d/bda56ddb489b34c5cb9ba783b19c112f/Hazel_sStory.mp4
